### ISSUE TITLE
Run nomad as non root user

### ISSUE THREAD

**Issue by mr-karan** [picatz/terraform-google-nomad#51]
Hi! 

I was referencing this repo for deploying a similar stack on AWS. I came across [install_nomad.sh#L27](https://github.com/picatz/terraform-google-nomad/blob/master/packer/scripts/install_nomad.sh#L27) and I think this is a typo. Should it not be owned by `nomad` user instead of `root` user? 

```
sudo chown --recursive nomad:nomad /nomad
```

**Comment by picatz** [comment]
👋 Hello @mr-karan -- great question! Apologies for the delay.

Indeed, you could choose to run Nomad as the `nomad` user/group. This is the [recommended](https://www.nomadproject.io/docs/internals/security#recommendations) way to run _server_ agents. However, to ensure the Docker driver works on the _client_ agent side, IIRC, you would also need to put the `nomad` user in the `docker` group, so that'd it'd be able to access the Docker socket. That is _essentially_ `root` privileges, in most cases.

I have Nomad running as the `root` user here to help ensure features, like CNI networking, just work™️. Some features expect elevated privileges. While it is possible to avoid doing this, and likely a good idea in most scenarios, it requires testing to ensure it doesn't break anything. It really depends on the use case.

**Comment by mr-karan** [comment]
Thanks for the explanation. Yep, that makes sense! I'll close it for now. 👍
